# -*- coding: utf-8 -*-
# 电赛历年真题 × 三大电子（消费/工业/车规）分类数据
# 数据来源：https://zuoliangyu.github.io/NUEDC_TOPIC/（GitHub 仓库 zuoliangyu/NUEDC_TOPIC，更新至2026）
# 领域标签：消费=消费电子，工业=工业电子，车规=车规电子（一道题可属多个领域）
# 优先级：1=重点推荐（直接对应公司产品/测试设备，单人可做，性价比高）
#         2=推荐（有公司化价值，但需较多设备/团队或偏训练）
#         3=参考（训练/兴趣价值为主）
# 分类为基于题目标题与公开资料的领域判定，公司化场景为落地建议。

TOPICS = [
# ============ 1994-2007 合集 ============
{"year": "1994-2007", "code": "合集", "title": "历年题目合集（1994-2007）",
 "sectors": ["消费", "工业", "车规"],
 "scene": "经典合集：含数控稳压电源、简易数字频率计、数字存储示波器、电阻电容电感测试仪、自动往返电动车、悬挂运动控制等，是电源/测量/控制三大基本功的源头题库",
 "priority": 2, "note": "网站上为合并PDF，未逐题拆分"},

# ============ 2009 ============
{"year": "2009", "code": "A", "title": "光伏并网发电模拟装置", "sectors": ["工业"],
 "scene": "光伏逆变器/并网逆变器的测试与模拟，新能源与储能企业直接对口", "priority": 2},
{"year": "2009", "code": "B", "title": "声音导引系统", "sectors": ["工业"],
 "scene": "声源定位、AGV/巡检机器人的声学导引", "priority": 2},
{"year": "2009", "code": "C", "title": "宽带直流放大器", "sectors": ["工业"],
 "scene": "示波器/频谱仪等测试仪器输入级、信号调理前端", "priority": 2},
{"year": "2009", "code": "D", "title": "无线环境监测模拟装置", "sectors": ["工业", "消费"],
 "scene": "环境监测物联网终端、智慧楼宇/仓储环境监测", "priority": 2},
{"year": "2009", "code": "E", "title": "电能收集充电器", "sectors": ["消费", "工业"],
 "scene": "能量收集电源、充电器/充电宝类电源产品", "priority": 2},
{"year": "2009", "code": "F", "title": "数字幅频均衡功率放大器", "sectors": ["消费"],
 "scene": "音频功放+EQ均衡，音响产品与音频测试", "priority": 2},
{"year": "2009", "code": "G", "title": "低频功率放大器", "sectors": ["消费", "工业"],
 "scene": "音频功放/功率驱动级", "priority": 2},
{"year": "2009", "code": "H", "title": "LED点阵书写显示屏", "sectors": ["消费", "工业"],
 "scene": "LED显示屏产品、电子黑板/写字板", "priority": 2},
{"year": "2009", "code": "I", "title": "模拟路灯控制系统", "sectors": ["工业", "消费"],
 "scene": "智慧路灯/智能照明控制系统", "priority": 2},

# ============ 2010 ============
{"year": "2010", "code": "A", "title": "无线家居监控系统", "sectors": ["消费"],
 "scene": "智能家居监控、家庭物联网网关", "priority": 2},
{"year": "2010", "code": "B", "title": "简易无线汉字传输装置", "sectors": ["消费", "工业"],
 "scene": "无线数传模块、短距通信设备", "priority": 3},
{"year": "2010", "code": "C", "title": "遥控绘图小车", "sectors": ["消费", "工业"],
 "scene": "教育机器人、绘图/写字设备", "priority": 3},
{"year": "2010", "code": "D", "title": "运动木棒长度计量装置", "sectors": ["工业"],
 "scene": "在线长度测量、工业计量设备", "priority": 2},
{"year": "2010", "code": "E", "title": "数控直流恒流电源", "sectors": ["工业", "消费"],
 "scene": "可编程电源/LED驱动电源，电源厂核心产品", "priority": 1},
{"year": "2010", "code": "F", "title": "低频频率特性测试仪", "sectors": ["工业"],
 "scene": "频率响应分析仪(FRA)、器件/放大器测试", "priority": 1},
{"year": "2010", "code": "G", "title": "DC-DC稳压电源（高职高专）", "sectors": ["消费", "工业"],
 "scene": "DC-DC电源模块、适配器", "priority": 1, "note": "高职组"},
{"year": "2010", "code": "H", "title": "正六面体端面特征自识别系统（高职高专）", "sectors": ["工业"],
 "scene": "机器视觉识别/分拣，产线外观检测", "priority": 2, "note": "高职组"},

# ============ 2011 ============
{"year": "2011", "code": "A", "title": "开关电源模块并联供电系统", "sectors": ["工业", "消费"],
 "scene": "电源冗余并联（服务器/通信电源），大功率电源系统", "priority": 1},
{"year": "2011", "code": "B", "title": "基于自由摆的平板控制系统", "sectors": ["工业"],
 "scene": "伺服/运动控制系统", "priority": 2},
{"year": "2011", "code": "C", "title": "智能小车", "sectors": ["消费", "工业", "车规"],
 "scene": "教育机器人/AGV/自动驾驶底盘雏形", "priority": 2},
{"year": "2011", "code": "D", "title": "LC谐振放大器", "sectors": ["工业"],
 "scene": "射频通信前端、选频放大", "priority": 3},
{"year": "2011", "code": "E", "title": "简易数字信号传输性能分析仪", "sectors": ["工业"],
 "scene": "通信测试仪器、误码/眼图分析", "priority": 2},
{"year": "2011", "code": "F", "title": "帆板控制系统", "sectors": ["工业"],
 "scene": "风机/风力发电控制、运动控制", "priority": 3},
{"year": "2011", "code": "G", "title": "简易自动电阻测试仪", "sectors": ["工业"],
 "scene": "元器件测试（电阻分选），电子厂来料检验设备", "priority": 1},
{"year": "2011", "code": "H", "title": "波形采集、存储与回放系统", "sectors": ["工业"],
 "scene": "数据采集卡、数字示波器", "priority": 1},

# ============ 2012 ============
{"year": "2012", "code": "A", "title": "微弱信号检测装置", "sectors": ["工业"],
 "scene": "精密测量仪器、传感器小信号调理", "priority": 2},
{"year": "2012", "code": "B", "title": "频率补偿电路", "sectors": ["工业"],
 "scene": "模拟电路设计/放大器稳定性补偿", "priority": 3},
{"year": "2012", "code": "C", "title": "简易直流电子负载", "sectors": ["工业"],
 "scene": "电子负载——电源厂/电池厂测试必备设备", "priority": 1},
{"year": "2012", "code": "D", "title": "声音定位系统", "sectors": ["工业", "消费"],
 "scene": "声学定位、会议系统/安防拾音", "priority": 2},
{"year": "2012", "code": "E", "title": "激光枪自动射击装置", "sectors": ["消费"],
 "scene": "光电玩具、射击游戏设备", "priority": 3},
{"year": "2012", "code": "F", "title": "便携式脉搏测试仪", "sectors": ["消费"],
 "scene": "健康监测、可穿戴设备", "priority": 2},
{"year": "2012", "code": "G", "title": "简易直流电子负载", "sectors": ["工业"],
 "scene": "电子负载（同2012-C）", "priority": 1, "note": "高职组，与C题重复"},
{"year": "2012", "code": "H", "title": "线阵LED图文显示装置", "sectors": ["消费", "工业"],
 "scene": "LED广告屏、风扇屏显示产品", "priority": 2},

# ============ 2013 ============
{"year": "2013", "code": "A", "title": "单相AC-DC变换电路", "sectors": ["消费", "工业", "车规"],
 "scene": "充电器/适配器、电源模块、车载充电机OBC（单相）", "priority": 1},
{"year": "2013", "code": "B", "title": "四旋翼自主飞行器", "sectors": ["工业", "消费"],
 "scene": "无人机巡检/航拍", "priority": 3},
{"year": "2013", "code": "C", "title": "简易旋转倒立摆及控制装置", "sectors": ["工业"],
 "scene": "运动控制/伺服算法验证平台", "priority": 2},
{"year": "2013", "code": "D", "title": "射频宽带放大器", "sectors": ["工业"],
 "scene": "射频测试/通信设备前端", "priority": 2},
{"year": "2013", "code": "E", "title": "简易频率特性测试仪", "sectors": ["工业"],
 "scene": "网络分析仪、器件频率特性测试", "priority": 1},
{"year": "2013", "code": "F", "title": "红外光通信装置", "sectors": ["消费", "工业"],
 "scene": "红外遥控/光通信链路", "priority": 3},
{"year": "2013", "code": "G", "title": "手写绘图板", "sectors": ["消费"],
 "scene": "数位板、触控输入设备", "priority": 2},
{"year": "2013", "code": "J", "title": "电磁控制运动装置", "sectors": ["工业"],
 "scene": "电磁执行器、精密运动控制", "priority": 2},
{"year": "2013", "code": "K", "title": "简易照明线路探测仪", "sectors": ["工业"],
 "scene": "电工施工检测仪器（验电/查线）", "priority": 2},
{"year": "2013", "code": "L", "title": "直流稳压电源及漏电保护装置", "sectors": ["工业", "消费"],
 "scene": "稳压电源+漏电保护（安全电子/家电电源）", "priority": 1},

# ============ 2014 ============
{"year": "2014", "code": "A", "title": "四旋翼飞行器", "sectors": ["工业", "消费"],
 "scene": "无人机巡检/航拍", "priority": 3},
{"year": "2014", "code": "B", "title": "金属物体探测定位器", "sectors": ["工业"],
 "scene": "安检/金属探测/工业异物检测", "priority": 2},
{"year": "2014", "code": "C", "title": "锁定放大器", "sectors": ["工业"],
 "scene": "锁相放大——精密测量仪器核心电路", "priority": 2},
{"year": "2014", "code": "D", "title": "音频功率放大器及啸叫抑制设计", "sectors": ["消费"],
 "scene": "音响/会议系统/公共广播，KTV与会议降啸叫", "priority": 2},
{"year": "2014", "code": "E", "title": "∑-Δ型ADC转换电路设计", "sectors": ["工业", "消费"],
 "scene": "高精度数据采集、音频ADC、仪表前端", "priority": 2},
{"year": "2014", "code": "F", "title": "电能无线传输装置", "sectors": ["消费", "车规", "工业"],
 "scene": "手机无线充电/车载无线充电/工业无线供电", "priority": 2},
{"year": "2014", "code": "G", "title": "风洞控制系统（高职高专）", "sectors": ["工业"],
 "scene": "风洞/风机性能测试台架", "priority": 2, "note": "高职组"},
{"year": "2014", "code": "H", "title": "自动增益控制放大器（高职高专）", "sectors": ["工业", "消费"],
 "scene": "接收机AGC、收音机/通信设备", "priority": 2, "note": "高职组"},

# ============ 2015 ============
{"year": "2015", "code": "A", "title": "双向DC-DC变换器", "sectors": ["车规", "工业", "消费"],
 "scene": "车载OBC/DCDC、储能双向变换、移动电源", "priority": 1},
{"year": "2015", "code": "B", "title": "风力摆控制系统", "sectors": ["工业"],
 "scene": "风机/运动控制算法验证", "priority": 3},
{"year": "2015", "code": "C", "title": "多旋翼自主飞行器", "sectors": ["工业", "消费"],
 "scene": "无人机巡检/航拍", "priority": 3},
{"year": "2015", "code": "D", "title": "增益可控射频放大器", "sectors": ["工业"],
 "scene": "射频测试/通信接收前端", "priority": 2},
{"year": "2015", "code": "E", "title": "80MHz-100MHz频谱仪", "sectors": ["工业"],
 "scene": "频谱分析仪（测试仪器）", "priority": 2},
{"year": "2015", "code": "F", "title": "数字频率计", "sectors": ["工业"],
 "scene": "通用频率/周期测量仪器", "priority": 1},
{"year": "2015", "code": "G", "title": "短距视频信号无线通信网络", "sectors": ["消费", "工业"],
 "scene": "无线图传、安防监控、无人机图传", "priority": 2},
{"year": "2015", "code": "H", "title": "LED闪光灯电源", "sectors": ["消费"],
 "scene": "手机闪光灯/摄影灯/LED照明驱动", "priority": 2},
{"year": "2015", "code": "I", "title": "风板控制装置", "sectors": ["工业"],
 "scene": "运动控制/风机控制", "priority": 3},
{"year": "2015", "code": "J", "title": "小球滚动控制系统", "sectors": ["工业"],
 "scene": "视觉伺服/运动控制平台", "priority": 2},

# ============ 2016 ============
{"year": "2016", "code": "A", "title": "降压型直流开关稳压电源", "sectors": ["消费", "工业", "车规"],
 "scene": "适配器/快充、DC-DC模块、车载DCDC——电源工程师入门必修", "priority": 1},
{"year": "2016", "code": "B", "title": "物品分拣搬送装置", "sectors": ["工业"],
 "scene": "自动化产线分拣、物流搬运", "priority": 2},
{"year": "2016", "code": "C", "title": "自动循迹小车", "sectors": ["消费", "工业", "车规"],
 "scene": "教育机器人/AGV/自动驾驶循迹", "priority": 2},
{"year": "2016", "code": "D", "title": "简易电子秤", "sectors": ["消费", "工业"],
 "scene": "电子秤、称重配料设备", "priority": 1},
{"year": "2016", "code": "E", "title": "脉冲信号参数测量仪", "sectors": ["工业"],
 "scene": "脉冲参数测试仪器", "priority": 1},
{"year": "2016", "code": "F", "title": "位同步时钟提取电路", "sectors": ["工业"],
 "scene": "通信数据恢复/时钟提取", "priority": 3},
{"year": "2016", "code": "G", "title": "简易电子秤（高职高专）", "sectors": ["消费", "工业"],
 "scene": "电子秤（同2016-D）", "priority": 1, "note": "高职组，与D题重复"},

# ============ 2017 ============
{"year": "2017", "code": "A", "title": "微电网模拟系统", "sectors": ["工业"],
 "scene": "微电网/储能/电力电子变流", "priority": 2},
{"year": "2017", "code": "B", "title": "滚球控制系统", "sectors": ["工业"],
 "scene": "运动控制/视觉伺服", "priority": 2},
{"year": "2017", "code": "C", "title": "四旋翼自主飞行器探测跟踪系统", "sectors": ["工业"],
 "scene": "无人机巡检/目标跟踪", "priority": 3},
{"year": "2017", "code": "E", "title": "自适应滤波器", "sectors": ["工业", "消费"],
 "scene": "主动降噪、信号去噪、回声消除", "priority": 2},
{"year": "2017", "code": "F", "title": "调幅信号处理实验电路", "sectors": ["工业"],
 "scene": "通信信号处理", "priority": 3},
{"year": "2017", "code": "H", "title": "远程幅频特性测试装置", "sectors": ["工业"],
 "scene": "远程测量仪器、网络化测试", "priority": 2},
{"year": "2017", "code": "I", "title": "可见光室内定位装置", "sectors": ["消费", "工业"],
 "scene": "室内定位、仓储/商场导航", "priority": 2},
{"year": "2017", "code": "K", "title": "单相用电器分析监测装置", "sectors": ["消费", "工业"],
 "scene": "非侵入式负荷识别NILM、智能电表/能耗管理", "priority": 1},
{"year": "2017", "code": "L", "title": "自动泊车系统", "sectors": ["车规"],
 "scene": "自动泊车APA——智能驾驶落地功能", "priority": 2},
{"year": "2017", "code": "M", "title": "管道内钢珠运动测量装置", "sectors": ["工业"],
 "scene": "管道检测、流体/物体运动测量", "priority": 2},
{"year": "2017", "code": "O", "title": "直流电动机测速装置", "sectors": ["工业", "车规", "消费"],
 "scene": "电机测速（家电电机/车载电机/工业电机），BLDC必备", "priority": 1},
{"year": "2017", "code": "P", "title": "简易水情检测系统", "sectors": ["工业", "消费"],
 "scene": "水文监测、家庭漏水检测", "priority": 2},

# ============ 2018 ============
{"year": "2018", "code": "A", "title": "电流信号检测装置", "sectors": ["工业"],
 "scene": "电流传感/检测，电源与电机测试", "priority": 1},
{"year": "2018", "code": "B", "title": "灭火飞行器", "sectors": ["工业"],
 "scene": "消防无人机", "priority": 3},
{"year": "2018", "code": "C", "title": "无线充电电动小车", "sectors": ["车规", "消费"],
 "scene": "无线充电（车载/手机）", "priority": 2},
{"year": "2018", "code": "D", "title": "手势识别", "sectors": ["消费"],
 "scene": "智能家居、体感交互设备", "priority": 2},
{"year": "2018", "code": "E", "title": "能量回收装置", "sectors": ["车规", "工业"],
 "scene": "制动能量回馈、节能装置", "priority": 2},
{"year": "2018", "code": "F", "title": "无线话筒扩音系统", "sectors": ["消费"],
 "scene": "无线麦克风、音响、会议系统", "priority": 2},
{"year": "2018", "code": "G", "title": "简易数字信号时序分析装置", "sectors": ["工业"],
 "scene": "逻辑分析仪", "priority": 2},
{"year": "2018", "code": "H", "title": "简易功率测量装置", "sectors": ["工业", "消费"],
 "scene": "功率计、家电/设备功耗测量", "priority": 1},

# ============ 2019 ============
{"year": "2019", "code": "A", "title": "电动小车动态无线充电系统", "sectors": ["车规"],
 "scene": "电动汽车动态无线充电（行业前沿）", "priority": 2},
{"year": "2019", "code": "B", "title": "巡线机器人", "sectors": ["工业"],
 "scene": "AGV巡检、产线运输机器人", "priority": 2},
{"year": "2019", "code": "C", "title": "线路负载及故障检测装置", "sectors": ["工业"],
 "scene": "电力线路检测、配电运维设备", "priority": 2},
{"year": "2019", "code": "D", "title": "简易电路特性测试仪", "sectors": ["工业"],
 "scene": "元器件/电路测试仪器", "priority": 1},
{"year": "2019", "code": "E", "title": "基于互联网的信号传输系统", "sectors": ["工业", "消费"],
 "scene": "物联网远程监控/数据采集上云", "priority": 2},
{"year": "2019", "code": "F", "title": "纸张计数显示装置", "sectors": ["工业"],
 "scene": "造纸/印刷/包装计数检测设备", "priority": 2},
{"year": "2019", "code": "G", "title": "双路语音同传的无线收发系统", "sectors": ["消费"],
 "scene": "同传耳机、无线麦克风", "priority": 2},
{"year": "2019", "code": "H", "title": "模拟电磁曲射炮", "sectors": ["消费"],
 "scene": "教育娱乐、电磁驱动展示", "priority": 3},
{"year": "2019", "code": "I", "title": "LED线阵显示装置", "sectors": ["消费", "工业"],
 "scene": "LED显示产品、广告屏", "priority": 2},
{"year": "2019", "code": "J", "title": "模拟电磁曲射炮（高职高专）", "sectors": ["消费"],
 "scene": "教育娱乐（同2019-H）", "priority": 3, "note": "高职组，与H题重复"},
{"year": "2019", "code": "K", "title": "简易多功能液体容器", "sectors": ["消费", "工业"],
 "scene": "智能水杯、液位检测", "priority": 2},

# ============ 2020 ============
{"year": "2020", "code": "A", "title": "无线运动传感器节点设计", "sectors": ["消费", "工业", "车规"],
 "scene": "可穿戴/设备状态监测/车辆运动监测（IoT传感器节点）", "priority": 2},
{"year": "2020", "code": "B", "title": "单相在线式不间断电源", "sectors": ["工业", "消费"],
 "scene": "UPS不间断电源——机房/设备供电保障", "priority": 1},
{"year": "2020", "code": "C", "title": "坡道行驶电动小车", "sectors": ["车规", "工业", "消费"],
 "scene": "电动车坡道控制、AGV爬坡", "priority": 2},
{"year": "2020", "code": "D", "title": "绕障飞行器", "sectors": ["工业"],
 "scene": "无人机避障", "priority": 3},
{"year": "2020", "code": "E", "title": "放大器非线性失真研究装置", "sectors": ["工业", "消费"],
 "scene": "功放/音频系统测试", "priority": 2},
{"year": "2020", "code": "F", "title": "简易无接触温度测量与身份识别装置", "sectors": ["消费", "工业"],
 "scene": "测温枪、门禁考勤、体温筛查", "priority": 2},
{"year": "2020", "code": "G", "title": "非接触物体尺寸形态测量", "sectors": ["工业"],
 "scene": "机器视觉在线尺寸检测", "priority": 2},

# ============ 2021 ============
{"year": "2021", "code": "A", "title": "信号失真度测量装置", "sectors": ["工业"],
 "scene": "失真度测试仪（音频/功放厂测试）", "priority": 1},
{"year": "2021", "code": "B", "title": "三相AC-DC变换电路", "sectors": ["工业", "车规"],
 "scene": "三相电源、车载充电机OBC（三相）", "priority": 1},
{"year": "2021", "code": "C", "title": "三端口DC-DC变换器", "sectors": ["车规", "工业", "消费"],
 "scene": "OBC+DCDC多端口电源、储能系统", "priority": 1},
{"year": "2021", "code": "D", "title": "基于互联网的摄像测量系统", "sectors": ["工业", "消费"],
 "scene": "机器视觉测量、安防监控", "priority": 2},
{"year": "2021", "code": "E", "title": "数字-模拟信号混合传输收发机", "sectors": ["工业"],
 "scene": "通信测试/收发信机", "priority": 2},
{"year": "2021", "code": "F", "title": "智能送药小车", "sectors": ["工业"],
 "scene": "医院物流机器人、AGV+视觉识别", "priority": 2},
{"year": "2021", "code": "G", "title": "植保飞行器", "sectors": ["工业"],
 "scene": "农业植保无人机", "priority": 3},
{"year": "2021", "code": "H", "title": "用电器分析识别装置", "sectors": ["消费", "工业"],
 "scene": "NILM负荷识别、智能电表/能耗管理", "priority": 1},
{"year": "2021", "code": "I", "title": "具有发电功能的储能小车", "sectors": ["车规", "消费"],
 "scene": "能量回收、储能装置", "priority": 2},
{"year": "2021", "code": "J", "title": "周期信号波形识别及参数测量装置", "sectors": ["工业"],
 "scene": "信号分析仪器", "priority": 1},
{"year": "2021", "code": "K", "title": "照度稳定可调LED台灯", "sectors": ["消费"],
 "scene": "护眼台灯/LED照明产品（闭环控制）", "priority": 1},

# ============ 2022 ============
{"year": "2022", "code": "A", "title": "单相交流电子负载", "sectors": ["工业"],
 "scene": "交流电子负载——电源/逆变器厂测试必备设备", "priority": 1},
{"year": "2022", "code": "B", "title": "送货无人机", "sectors": ["工业"],
 "scene": "物流无人机", "priority": 3},
{"year": "2022", "code": "C", "title": "小车跟随行驶系统", "sectors": ["车规", "工业"],
 "scene": "车辆编队、ACC跟车、AGV协同", "priority": 2},
{"year": "2022", "code": "D", "title": "混沌信号发生器", "sectors": ["工业"],
 "scene": "信号源、加密通信", "priority": 2},
{"year": "2022", "code": "E", "title": "声源定位跟踪系统", "sectors": ["工业", "车规"],
 "scene": "声学检测、车载语音定位、安防", "priority": 2},
{"year": "2022", "code": "F", "title": "信号调制度测量装置", "sectors": ["工业"],
 "scene": "通信测量仪器", "priority": 2},
{"year": "2022", "code": "G", "title": "单相交流负载模拟单元", "sectors": ["工业"],
 "scene": "负载模拟——电源/逆变器测试", "priority": 1},
{"year": "2022", "code": "H", "title": "小车跟随行驶系统", "sectors": ["车规", "工业"],
 "scene": "车辆编队（同2022-C）", "priority": 2, "note": "与C题重复"},
{"year": "2022", "code": "I", "title": "声源定位跟踪系统", "sectors": ["工业", "车规"],
 "scene": "声学定位（同2022-E）", "priority": 2, "note": "与E题重复"},

# ============ 2023 ============
{"year": "2023", "code": "A", "title": "单相逆变器并联运行系统", "sectors": ["工业", "车规"],
 "scene": "逆变器/UPS/储能并联、车载逆变", "priority": 1},
{"year": "2023", "code": "B", "title": "同轴电缆长度与终端负载检测装置", "sectors": ["工业", "车规"],
 "scene": "线缆测试、车载线束/同轴线束检测", "priority": 2},
{"year": "2023", "code": "C", "title": "电感电容测量装置", "sectors": ["工业"],
 "scene": "LCR表——元器件厂/来料检验必备仪器", "priority": 1},
{"year": "2023", "code": "D", "title": "信号调制方式识别与参数估计装置", "sectors": ["工业"],
 "scene": "频谱监测、通信侦察", "priority": 2},
{"year": "2023", "code": "E", "title": "运动目标控制与自动追踪系统", "sectors": ["工业", "车规"],
 "scene": "云台伺服、视觉目标追踪", "priority": 2},
{"year": "2023", "code": "F", "title": "基于声传播的智能定位系统", "sectors": ["工业"],
 "scene": "声学定位、室内定位", "priority": 2},
{"year": "2023", "code": "G", "title": "空地协同智能消防系统", "sectors": ["工业"],
 "scene": "消防应急、空地协同", "priority": 3},
{"year": "2023", "code": "H", "title": "信号分离装置", "sectors": ["工业"],
 "scene": "信号处理/盲源分离", "priority": 2},
{"year": "2023", "code": "I", "title": "气垫悬浮车", "sectors": ["工业"],
 "scene": "磁悬浮、精密运动控制", "priority": 2},
{"year": "2023", "code": "J", "title": "线路故障自动检测系统", "sectors": ["工业"],
 "scene": "配电线路检测运维", "priority": 2},
{"year": "2023", "code": "K", "title": "辨音识键奏乐系统", "sectors": ["消费"],
 "scene": "音乐教育、娱乐交互", "priority": 3},

# ============ 2024 ============
{"year": "2024", "code": "A", "title": "AC-AC变换电路并联运行", "sectors": ["工业", "消费"],
 "scene": "调压器、变频电源、家电调压", "priority": 1},
{"year": "2024", "code": "B", "title": "单相功率分析仪", "sectors": ["工业"],
 "scene": "功率分析仪——电源/家电能效测试必备", "priority": 1},
{"year": "2024", "code": "C", "title": "无线传输信号模拟系统", "sectors": ["工业"],
 "scene": "信道模拟、通信测试", "priority": 2},
{"year": "2024", "code": "D", "title": "立体货架盘点无人机系统", "sectors": ["工业"],
 "scene": "仓储盘点、无人机视觉", "priority": 3},
{"year": "2024", "code": "E", "title": "三子棋游戏装置", "sectors": ["消费"],
 "scene": "娱乐/教育设备", "priority": 3},
{"year": "2024", "code": "F", "title": "磁悬浮实验装置", "sectors": ["工业"],
 "scene": "磁悬浮、精密运动控制", "priority": 2},
{"year": "2024", "code": "G", "title": "简易录音屏蔽系统", "sectors": ["消费", "工业"],
 "scene": "隐私保护、防窃听设备", "priority": 2},
{"year": "2024", "code": "H", "title": "自动行驶小车", "sectors": ["车规", "工业"],
 "scene": "自动驾驶底盘、AGV", "priority": 2},

# ============ 2025 ============
{"year": "2025", "code": "A", "title": "能量回馈的变流器负载试验装置", "sectors": ["工业", "车规"],
 "scene": "变流器测试负载（能量回馈）——电源/电驱测试节能设备", "priority": 1},
{"year": "2025", "code": "B", "title": "单相有源电力滤波实验装置", "sectors": ["工业"],
 "scene": "APF电能质量治理设备", "priority": 2},
{"year": "2025", "code": "C", "title": "基于单目视觉的目标物测量装置", "sectors": ["工业", "车规"],
 "scene": "机器视觉测量、ADAS单目测距", "priority": 2},
{"year": "2025", "code": "D", "title": "简易以太网双绞线测试仪", "sectors": ["工业", "车规"],
 "scene": "网络布线测试、车载以太网线束测试（行业热点）", "priority": 2},
{"year": "2025", "code": "E", "title": "简易自行瞄准装置", "sectors": ["工业"],
 "scene": "伺服云台、光电跟踪", "priority": 2},
{"year": "2025", "code": "F", "title": "简易自动接收机", "sectors": ["工业"],
 "scene": "通信接收机、软件无线电SDR", "priority": 2},
{"year": "2025", "code": "G", "title": "电路模型探究装置", "sectors": ["工业"],
 "scene": "教学仪器（偏训练）", "priority": 3},
{"year": "2025", "code": "H", "title": "野生动物巡查系统", "sectors": ["工业"],
 "scene": "无人机巡检、安防监控", "priority": 3},

# ============ 2026 ============
{"year": "2026", "code": "A", "title": "AC-AC变换电路", "sectors": ["工业", "消费"],
 "scene": "调压器、变频电源", "priority": 1},
{"year": "2026", "code": "B", "title": "“无源”交流电流表及无线读表器", "sectors": ["工业", "消费"],
 "scene": "电流互感器/无线抄表/智能电表（无源取电技术）", "priority": 1},
{"year": "2026", "code": "C", "title": "基于无线通信的数字钥匙实验系统", "sectors": ["车规", "消费"],
 "scene": "数字钥匙（UWB/BLE）——车规热点，也适用智能门锁", "priority": 1},
{"year": "2026", "code": "D", "title": "陆空协同无人机系统", "sectors": ["工业"],
 "scene": "无人机、空地协同", "priority": 3},
{"year": "2026", "code": "E", "title": "拼图装置", "sectors": ["消费", "工业"],
 "scene": "教育娱乐、视觉定位", "priority": 3},
{"year": "2026", "code": "F", "title": "李萨如图形显示控制装置", "sectors": ["工业", "消费"],
 "scene": "示波器显示、显示器测试", "priority": 2},
{"year": "2026", "code": "G", "title": "周期信号测量分析装置", "sectors": ["工业"],
 "scene": "信号分析仪器", "priority": 1},
{"year": "2026", "code": "H", "title": "车载平衡滚球运动控制系统", "sectors": ["车规", "工业"],
 "scene": "车载惯性稳定、运动控制", "priority": 2},

# ============ 综合测评 ============
{"year": "综合测评", "code": "合集", "title": "综合测评合集（2011-2025模拟电路）", "sectors": ["消费", "工业", "车规"],
 "scene": "运放/波形产生/滤波等模拟电路基本功，三大方向通用必修，配合TI模拟手册学习",
 "priority": 2, "note": "2011/2013/2015/2017/2019/2021/2023/2025 八届综测"},
]
